/*
 * Voitheia API
 * Api for Voitheia. Developed for the WeVsVirus hackathon
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.voitheia.api;

import com.voitheia.api.invoker.ApiException;
import com.voitheia.api.model.CreateRequestDto;
import com.voitheia.api.model.CreateRequestResponseDto;
import com.voitheia.api.model.GetAllRequestResponse;
import com.voitheia.api.model.GetRequestResponse;
import com.voitheia.api.model.ProblemDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RequestApi
 */
@Ignore
public class RequestApiTest {

    private final RequestApi api = new RequestApi();

    
    /**
     * Get all requests in a specific area if longitude and latitude is not given,  the registered address of the user is taken
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestGetTest() throws ApiException {
        Double longitude = null;
        Double latitude = null;
        Integer amount = null;
        Integer metersPerimeter = null;
        GetAllRequestResponse response = api.requestGet(longitude, latitude, amount, metersPerimeter);

        // TODO: test validations
    }
    
    /**
     * Removes a request from the Database
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestIdDeleteTest() throws ApiException {
        Integer id = null;
        api.requestIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * Get request by id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestIdGetTest() throws ApiException {
        Integer id = null;
        GetRequestResponse response = api.requestIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Inserts a request to the database  Returns 201 if success  Returns 400 if the Request dto was malformed  Returns 424 if the Address was invalid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestPostTest() throws ApiException {
        CreateRequestDto createRequestDto = null;
        CreateRequestResponseDto response = api.requestPost(createRequestDto);

        // TODO: test validations
    }
    
}
