/*
 * Voitheia API
 * Api for Voitheia. Developed for the WeVsVirus hackathon
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.voitheia.api;

import com.voitheia.api.invoker.ApiException;
import com.voitheia.api.model.CredentialsDTO;
import com.voitheia.api.model.JwtDto;
import com.voitheia.api.model.RegisterUserDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Indicates whether or not a User is logged in
     *
     * When the code reachis this function the user was successfully logged in through Windows authentication.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiUserLoggedInGetTest() throws ApiException {
        api.apiUserLoggedInGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiUserLoginPostTest() throws ApiException {
        CredentialsDTO credentialsDTO = null;
        JwtDto response = api.apiUserLoginPost(credentialsDTO);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiUserRegisterPostTest() throws ApiException {
        RegisterUserDTO registerUserDTO = null;
        JwtDto response = api.apiUserRegisterPost(registerUserDTO);

        // TODO: test validations
    }
    
}
