/*
 * Voitheia API
 * Api for Voitheia. Developed for the WeVsVirus hackathon
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.voitheia.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.voitheia.api.model.PatchRequestStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PatchRequestDto
 */
public class PatchRequestDtoTest {
    private final PatchRequestDto model = new PatchRequestDto();

    /**
     * Model tests for PatchRequestDto
     */
    @Test
    public void testPatchRequestDto() {
        // TODO: test PatchRequestDto
    }

    /**
     * Test the property 'newRequestStatus'
     */
    @Test
    public void newRequestStatusTest() {
        // TODO: test newRequestStatus
    }

}
