/*
 * Voitheia API
 * Api for Voitheia. Developed for the WeVsVirus hackathon
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.voitheia.api.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RequestType
 */
public class RequestTypeTest {
    /**
     * Model tests for RequestType
     */
    @Test
    public void testRequestType() {
        // TODO: test RequestType
    }

}
