/**
* Voitheia API
* Api for Voitheia. Developed for the WeVsVirus hackathon
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.voitheia.api.model

import com.voitheia.api.model.RequestType

import com.squareup.moshi.Json
/**
 * The DTO for requests
 * @param type 
 * @param lastName The last name of the person who needs help
 * @param firstName The first name of the person who needs help
 * @param email The email of the person who needs help
 * @param phoneNumber The phone number of the person who needs help
 * @param street The street address of the person who needs help
 * @param zip The zip of the person who needs help
 * @param city The city of the person who needs help
 * @param description Comment for the request
 */

data class CreateRequestDto (
    @Json(name = "type")
    val type: RequestType,
    /* The last name of the person who needs help */
    @Json(name = "lastName")
    val lastName: kotlin.String,
    /* The first name of the person who needs help */
    @Json(name = "firstName")
    val firstName: kotlin.String,
    /* The email of the person who needs help */
    @Json(name = "email")
    val email: kotlin.String? = null,
    /* The phone number of the person who needs help */
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,
    /* The street address of the person who needs help */
    @Json(name = "street")
    val street: kotlin.String? = null,
    /* The zip of the person who needs help */
    @Json(name = "zip")
    val zip: kotlin.String? = null,
    /* The city of the person who needs help */
    @Json(name = "city")
    val city: kotlin.String? = null,
    /* Comment for the request */
    @Json(name = "description")
    val description: kotlin.String? = null
) 



