/**
* Voitheia API
* Api for Voitheia. Developed for the WeVsVirus hackathon
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.voitheia.api.model


import com.squareup.moshi.Json
/**
 * 
 * @param email 
 * @param password 
 */

data class CredentialsDTO (
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "password")
    val password: kotlin.String
) 



