/**
* Voitheia API
* Api for Voitheia. Developed for the WeVsVirus hackathon
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.voitheia.api.model

import com.voitheia.api.model.RequestDto

import com.squareup.moshi.Json
/**
 * 
 * @param request 
 */

data class GetRequestResponse (
    @Json(name = "request")
    val request: RequestDto? = null
) 



