/**
* Voitheia API
* Api for Voitheia. Developed for the WeVsVirus hackathon
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.voitheia.api.model


import com.squareup.moshi.Json

/**
* The status of the request
* Values: open,assigned,closed
*/

enum class RequestStatus(val value: kotlin.String){


    @Json(name = "Open")
    open("Open"),


    @Json(name = "Assigned")
    assigned("Assigned"),


    @Json(name = "Closed")
    closed("Closed");



}

