/**
* Voitheia API
* Api for Voitheia. Developed for the WeVsVirus hackathon
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.voitheia.api.model

import com.voitheia.api.model.RequestStatus
import com.voitheia.api.model.RequestType

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param description 
 * @param email 
 * @param firstName 
 * @param lastName 
 * @param phoneNumber 
 * @param street 
 * @param zip 
 * @param city 
 * @param status 
 * @param distanceToUser Distance to the currently logged in users registered address
 * @param type 
 */

data class RequestDto (
    @Json(name = "id")
    val id: kotlin.Int? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "firstName")
    val firstName: kotlin.String? = null,
    @Json(name = "lastName")
    val lastName: kotlin.String? = null,
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,
    @Json(name = "street")
    val street: kotlin.String? = null,
    @Json(name = "zip")
    val zip: kotlin.String? = null,
    @Json(name = "city")
    val city: kotlin.String? = null,
    @Json(name = "status")
    val status: RequestStatus? = null,
    /* Distance to the currently logged in users registered address */
    @Json(name = "distanceToUser")
    val distanceToUser: kotlin.Int? = null,
    @Json(name = "type")
    val type: RequestType? = null
) 



